version: "3.4"

services:
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: builder
      POSTGRES_PASSWORD: builder
    ports:
      - 5432:5432
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2019-08-07T01-59-21Z
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./.data/miniodata:/data
    environment:
      MINIO_ACCESS_KEY: SYmuS-lZ3J39PjejLCiZ
      MINIO_SECRET_KEY: 5yGXYIjUTw5aecYgGoBudpMs0drw26csJY39dVkR

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx
    command: ./start.sh

  saver:
    build: 
      context: ./src
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/app
      - /app/bin/
      - /app/obj/
      - /app/ClientApp/node_modules
    environment: 
      - TZ=Europe/Moscow
      - BUCKET=backups 
      - ACCESS_KEY=SYmuS-lZ3J39PjejLCiZ 
      - SECRET_KEY=5yGXYIjUTw5aecYgGoBudpMs0drw26csJY39dVkR 
      - TELEGRAM_CONNECTION_STRING=https://integram.org/webhook/cgn2U1gAsjC 
      - S3_CONNECTION_STRING=http://minio:9000 
      - FILE_DELETION_PERIOD_IN_DAYS=7 
      - DB_USER_NAME=builder 
      - DB_PASSWORD=builder 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_IGNORE=postgres,builder,template1,template0
      - SENTRY_CONNECTION_STRING=https://8e386e8cca8c450e85edda1c46469a9a@o421804.ingest.sentry.io/5342167 
      - PASSWORD=1234
      - LOGIN=hello
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    ports: 
      - 5000:5000
      - 5001:5001
    command: sh -c 'dotnet watch run --no-launch-profile'
  
  adminer:
    image: adminer

  